version: "3.9"
services:
  server:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
  redis:
    image: redis
